_base_: "configs/base.yaml"

data:
  img_size: [224, 224]
  batch_size: 32

model:
  backbone: "ConvNeXtTiny"
  pretrained: "imagenet"
  pooling: "avg"
  dropout: 0.3
  classifier:
    hidden_units: [512]
    activation: "relu"
    l2: 1.0e-5
    output_activation: "sigmoid"

training:
  epochs: 50
  optimizer: "adamw"
  learning_rate: 3.0e-4
  weight_decay: 1.0e-4
