_base_: "configs/base.yaml"

model:
  backbone: "DenseNet201"
  pretrained: "imagenet"
  pooling: "avg"
  dropout: 0.4
  classifier:
    hidden_units: [512]
    activation: "relu"
    l2: 1.0e-5
    output_activation: "sigmoid"

training:
  epochs: 60
  optimizer: "adam"
  learning_rate: 1.0e-4
