_base_: "configs/base.yaml"

data:
  img_size: [299, 299]
  batch_size: 24

model:
  backbone: "InceptionV3"
  pretrained: "imagenet"
  pooling: "avg"
  dropout: 0.4
  classifier:
    hidden_units: [1024]
    activation: "relu"
    l2: 1.0e-5
    output_activation: "sigmoid"

training:
  epochs: 60
  optimizer: "adam"
  learning_rate: 2.0e-4
